### 실제 파일로 업로드
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=test-file-upload

--test-file-upload
Content-Disposition: form-data; name="file"; filename="test.txt"

# 텍스트 파일 지정
< test.txt
--test-file-upload--



### 사진 업로드
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=image-file-upload

--image-file-upload
Content-Disposition: form-data; name="file"; filename="cat.jpg"
Content-Type: image/jpeg

< cat.jpg
--image-file-upload--
