POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "andy",
  "password": "test1234",
  "email": "andy@podo.com"
}

GET http://localhost:3000/user/getUser/andy@podo.localhost:3000/person/andy@podo.com

PUT http://localhost:3000/user/update/andy@podo.com
content-type: application/json

{
  "email": "andy@podo.com",
  "username": "andy2",
  "password": "test12345"
}

DELETE http://localhost:3000/user/delete/andy@podo.com

POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "andy",
  "password": "test1234",
  "email": "andy-podo"
}