# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-service-students14

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  deploymentBucket:
    name: tmd-genai1-students14
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    USERS_TABLE: ${self:service}-users-${sls:stage} # my-service-students14-users-dev

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: post

  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
